# Generated by Django 2.0.3 on 2018-03-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='short_url',
            field=models.URLField(null=True),
        ),
    ]
