# Generated by Django 2.0.3 on 2018-03-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_testmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
