# Generated by Django 2.0.3 on 2018-03-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_testmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmodel',
            name='test_models',
            field=models.ManyToManyField(blank=True, related_name='_testmodel_test_models_+', to='polls.TestModel'),
        ),
    ]
