# Generated by Django 2.0.3 on 2018-03-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeldemoapp', '0002_auto_20180329_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
