# Generated by Django 2.0.3 on 2018-03-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20180326_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('checkin_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('book_user', models.CharField(max_length=150)),
                ('is_checked_out', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
