# Generated by Django 2.0.3 on 2018-03-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_auto_20180314_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='completed',
        ),
    ]
