# Generated by Django 2.0.3 on 2018-03-15 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab02_todo', '0004_auto_20180315_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='complete_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
