# Generated by Django 2.0.3 on 2018-03-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab02_todo', '0006_auto_20180315_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='complete_date',
            new_name='completed_date',
        ),
    ]
