# Generated by Django 2.0.3 on 2018-03-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab02_todo', '0007_auto_20180315_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='created_date',
        ),
    ]
