# Generated by Django 2.0.3 on 2018-03-15 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
