# Generated by Django 2.0.3 on 2018-03-21 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20180320_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list',
            options={},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
    ]
