# Generated by Django 2.0.3 on 2018-03-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20180321_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_list',
        ),
    ]
