# Generated by Django 2.0.3 on 2018-03-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_remove_todo_todo_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
