# Generated by Django 2.0.3 on 2018-03-16 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MadLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MadLibWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('madlib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madlibapp.MadLib')),
            ],
        ),
        migrations.CreateModel(
            name='MadLibWordType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='madlibword',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='madlibapp.MadLibWordType'),
        ),
    ]
