# Generated by Django 2.0.3 on 2018-03-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_note_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='completed_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='note',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name=False),
        ),
    ]
