# Generated by Django 2.0.3 on 2018-03-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20180319_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='completed_date',
            new_name='edited_date',
        ),
    ]
