# Generated by Django 2.0.3 on 2018-03-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_auto_20180319_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='edited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
