# Generated by Django 2.0.3 on 2018-03-25 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlib', '0002_auto_20180325_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
