# Generated by Django 2.0.3 on 2018-03-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlib', '0003_auto_20180325_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='timestamp_in',
        ),
        migrations.RemoveField(
            model_name='history',
            name='timestamp_out',
        ),
        migrations.AddField(
            model_name='history',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
