# Generated by Django 2.0.3 on 2018-03-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlib', '0004_auto_20180325_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available',
        ),
        migrations.AddField(
            model_name='history',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
