# Generated by Django 2.0.3 on 2018-03-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newlib', '0006_auto_20180325_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='history',
            name='time_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
