# Generated by Django 2.0.3 on 2018-03-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateTimeField()),
                ('favorite_number', models.FloatField()),
                ('favorite_fruit', models.CharField(max_length=100)),
                ('favorite_color', models.CharField(max_length=100)),
            ],
        ),
    ]
