# Generated by Django 2.0.3 on 2018-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
