print("Welcome to the maddest of Mad Libs")
loc = input("Give me a location\n:")
verb = input("Give me a verb\n:")
num = input("Give me a number\n:")
pet = input("What is your favorite animal?\n:")
food = input("What is your favorite food?\n:")
print("Great! Let's see what we have.")
print("Now seeking " + pet + " in the " + loc + " area. Needed for " + verb + " training. Will pay in " + food + " or $" + num)