# Generated by Django 2.0.3 on 2018-03-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_url', models.URLField()),
                ('short_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
