# Generated by Django 2.0.3 on 2018-03-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='btn_selected',
            field=models.BooleanField(default=False),
        ),
    ]
