# Generated by Django 2.0.3 on 2018-03-13 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_text', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(verbose_name='date created')),
                ('date_completed', models.DateTimeField(verbose_name='date completed')),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
